# Site settings
title: Not A Number
#email: your-email@example.com
description: > # this means to ignore newlines in the text below
url: "http://example.com" # the base hostname & protocol for your site
#twitter_username:
#github_username:
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
exclude: ['*.Rmd']
